name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
      - master
      - gh_action_test
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
            node-version: 14
      - name: Install node dependencies
        run: npm install
      - name: Annotate
        env:
          GITHUB_RUN_ID: ${{GITHUB_RUN_ID}}
          APP_ID: ${{secrets.APP_ID}}
          APP_INSTALL_ID: ${{secrets.APP_INSTALL_ID}}
          APP_CLIENT_ID: ${{secrets.APP_CLIENT_ID}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          APP_KEY: ${{secrets.APP_KEY}}
          APP_SECRET: ${{secrets.APP_SECRET}}
        run: node annotate.js
        
      
