name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
      - master
      - gh_action_test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
            node-version: 12
      - name: Setup Node Environment
        run: npm install
        run: npm run-script build
      - name: Annotate
        run: node dist/annotate.js
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
