name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
      - master
      - gh_action_test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarxDev/ast-github-action@master #Github Action version
        with:
          base_uri: https://ast-master.dev.cxast.net
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.SECRET }}
          project_name: GHTest1018
          cx_tenant: organization
