name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
      - master
      - gh_action_test
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
            node-version: 14
      - name: Install node dependencies
        run: npm install
      - name: Annotate
        run: node annotate.js
        env:
          JEFF: "foo"
          GITHUB_TOKEN: ${secrets.GITHUB_TOKEN}
      